// RSS source configurations for English foreign publications
// Each source defines the feed URL, metadata, and category

const SOURCES = [
  {
    name: 'BBC News',
    slug: 'bbc',
    url: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    category: 'World',
    language: 'en',
    color: '#bb1919',
  },
  {
    name: 'BBC Technology',
    slug: 'bbc-tech',
    url: 'https://feeds.bbci.co.uk/news/technology/rss.xml',
    category: 'Technology',
    language: 'en',
    color: '#bb1919',
  },
  {
    name: 'BBC Business',
    slug: 'bbc-business',
    url: 'https://feeds.bbci.co.uk/news/business/rss.xml',
    category: 'Business',
    language: 'en',
    color: '#bb1919',
  },
  {
    name: 'NPR',
    slug: 'npr',
    url: 'https://feeds.npr.org/1001/rss.xml',
    category: 'General',
    language: 'en',
    color: '#e7792b',
  },
  {
    name: 'The Guardian',
    slug: 'guardian',
    url: 'https://www.theguardian.com/world/rss',
    category: 'World',
    language: 'en',
    color: '#052962',
  },
  {
    name: 'The Guardian Technology',
    slug: 'guardian-tech',
    url: 'https://www.theguardian.com/technology/rss',
    category: 'Technology',
    language: 'en',
    color: '#052962',
  },
  {
    name: 'Scientific American',
    slug: 'sciam',
    url: 'https://www.scientificamerican.com/feed/rss.xml',
    category: 'Science',
    language: 'en',
    color: '#00a86b',
  },
  {
    name: 'Science Daily',
    slug: 'sciencedaily',
    url: 'https://www.sciencedaily.com/rss/top/science.xml',
    category: 'Science',
    language: 'en',
    color: '#4b7ba5',
  },
  {
    name: 'PBS NewsHour',
    slug: 'pbs',
    url: 'https://www.pbs.org/newshour/feeds/rss/headlines',
    category: 'General',
    language: 'en',
    color: '#1d5a93',
  },
  {
    name: 'MIT Technology Review',
    slug: 'mit-tr',
    url: 'https://www.technologyreview.com/feed/',
    category: 'Technology',
    language: 'en',
    color: '#000000',
  },
  {
    name: 'Aeon',
    slug: 'aeon',
    url: 'https://aeon.co/feed.rss',
    category: 'Culture',
    language: 'en',
    color: '#4a4a4a',
  },
  {
    name: 'Smithsonian Magazine',
    slug: 'smithsonian',
    url: 'https://www.smithsonianmag.com/rss/latest_articles/',
    category: 'Culture',
    language: 'en',
    color: '#c41230',
  },
  {
    name: 'Popular Science',
    slug: 'popsci',
    url: 'https://www.popsci.com/feed/',
    category: 'Science',
    language: 'en',
    color: '#1a1a1a',
  },
  {
    name: 'Quanta Magazine',
    slug: 'quanta',
    url: 'https://www.quantamagazine.org/feed/',
    category: 'Science',
    language: 'en',
    color: '#2d6ca2',
  },
];

module.exports = SOURCES;
